/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type BaseRewardRouterRewards = { rewards: bigint };

export type BaseRewardRouterRewardsArgs = { rewards: number | bigint };

export function getBaseRewardRouterRewardsEncoder(): Encoder<BaseRewardRouterRewardsArgs> {
  return getStructEncoder([['rewards', getU64Encoder()]]);
}

export function getBaseRewardRouterRewardsDecoder(): Decoder<BaseRewardRouterRewards> {
  return getStructDecoder([['rewards', getU64Decoder()]]);
}

export function getBaseRewardRouterRewardsCodec(): Codec<
  BaseRewardRouterRewardsArgs,
  BaseRewardRouterRewards
> {
  return combineCodec(
    getBaseRewardRouterRewardsEncoder(),
    getBaseRewardRouterRewardsDecoder()
  );
}
