/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type Fee = { fee: number };

export type FeeArgs = Fee;

export function getFeeEncoder(): Encoder<FeeArgs> {
  return getStructEncoder([['fee', getU16Encoder()]]);
}

export function getFeeDecoder(): Decoder<Fee> {
  return getStructDecoder([['fee', getU16Decoder()]]);
}

export function getFeeCodec(): Codec<FeeArgs, Fee> {
  return combineCodec(getFeeEncoder(), getFeeDecoder());
}
