/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type JitoNumber = { value: Array<number> };

export type JitoNumberArgs = JitoNumber;

export function getJitoNumberEncoder(): Encoder<JitoNumberArgs> {
  return getStructEncoder([
    ['value', getArrayEncoder(getU8Encoder(), { size: 16 })],
  ]);
}

export function getJitoNumberDecoder(): Decoder<JitoNumber> {
  return getStructDecoder([
    ['value', getArrayDecoder(getU8Decoder(), { size: 16 })],
  ]);
}

export function getJitoNumberCodec(): Codec<JitoNumberArgs, JitoNumber> {
  return combineCodec(getJitoNumberEncoder(), getJitoNumberDecoder());
}
