/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type MintEntry = {
  stMint: Address;
  vaultIndex: bigint;
  weight: bigint;
  slotSet: bigint;
  slotUpdated: bigint;
  reserved: Array<number>;
};

export type MintEntryArgs = {
  stMint: Address;
  vaultIndex: number | bigint;
  weight: number | bigint;
  slotSet: number | bigint;
  slotUpdated: number | bigint;
  reserved: Array<number>;
};

export function getMintEntryEncoder(): Encoder<MintEntryArgs> {
  return getStructEncoder([
    ['stMint', getAddressEncoder()],
    ['vaultIndex', getU64Encoder()],
    ['weight', getU128Encoder()],
    ['slotSet', getU64Encoder()],
    ['slotUpdated', getU64Encoder()],
    ['reserved', getArrayEncoder(getU8Encoder(), { size: 128 })],
  ]);
}

export function getMintEntryDecoder(): Decoder<MintEntry> {
  return getStructDecoder([
    ['stMint', getAddressDecoder()],
    ['vaultIndex', getU64Decoder()],
    ['weight', getU128Decoder()],
    ['slotSet', getU64Decoder()],
    ['slotUpdated', getU64Decoder()],
    ['reserved', getArrayDecoder(getU8Decoder(), { size: 128 })],
  ]);
}

export function getMintEntryCodec(): Codec<MintEntryArgs, MintEntry> {
  return combineCodec(getMintEntryEncoder(), getMintEntryDecoder());
}
