/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type MintEntry = { stMint: Address; vaultIndex: bigint };

export type MintEntryArgs = { stMint: Address; vaultIndex: number | bigint };

export function getMintEntryEncoder(): Encoder<MintEntryArgs> {
  return getStructEncoder([
    ['stMint', getAddressEncoder()],
    ['vaultIndex', getU64Encoder()],
  ]);
}

export function getMintEntryDecoder(): Decoder<MintEntry> {
  return getStructDecoder([
    ['stMint', getAddressDecoder()],
    ['vaultIndex', getU64Decoder()],
  ]);
}

export function getMintEntryCodec(): Codec<MintEntryArgs, MintEntry> {
  return combineCodec(getMintEntryEncoder(), getMintEntryDecoder());
}
