/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type NcnFeeGroupWeight = { weight: bigint };

export type NcnFeeGroupWeightArgs = { weight: number | bigint };

export function getNcnFeeGroupWeightEncoder(): Encoder<NcnFeeGroupWeightArgs> {
  return getStructEncoder([['weight', getU128Encoder()]]);
}

export function getNcnFeeGroupWeightDecoder(): Decoder<NcnFeeGroupWeight> {
  return getStructDecoder([['weight', getU128Decoder()]]);
}

export function getNcnFeeGroupWeightCodec(): Codec<
  NcnFeeGroupWeightArgs,
  NcnFeeGroupWeight
> {
  return combineCodec(
    getNcnFeeGroupWeightEncoder(),
    getNcnFeeGroupWeightDecoder()
  );
}
