/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';
import {
  getPreciseNumberWrapperDecoder,
  getPreciseNumberWrapperEncoder,
  type PreciseNumberWrapper,
  type PreciseNumberWrapperArgs,
} from '.';

export type PreciseWeight = { number: PreciseNumberWrapper };

export type PreciseWeightArgs = { number: PreciseNumberWrapperArgs };

export function getPreciseWeightEncoder(): Encoder<PreciseWeightArgs> {
  return getStructEncoder([['number', getPreciseNumberWrapperEncoder()]]);
}

export function getPreciseWeightDecoder(): Decoder<PreciseWeight> {
  return getStructDecoder([['number', getPreciseNumberWrapperDecoder()]]);
}

export function getPreciseWeightCodec(): Codec<
  PreciseWeightArgs,
  PreciseWeight
> {
  return combineCodec(getPreciseWeightEncoder(), getPreciseWeightDecoder());
}
