/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const ADMIN_UPDATE_WEIGHT_TABLE_DISCRIMINATOR = 4;

export function getAdminUpdateWeightTableDiscriminatorBytes() {
  return getU8Encoder().encode(ADMIN_UPDATE_WEIGHT_TABLE_DISCRIMINATOR);
}

export type AdminUpdateWeightTableInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountWeightTable extends string | IAccountMeta<string> = string,
  TAccountWeightTableAdmin extends string | IAccountMeta<string> = string,
  TAccountMint extends string | IAccountMeta<string> = string,
  TAccountRestakingProgramId extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountWeightTable extends string
        ? WritableAccount<TAccountWeightTable>
        : TAccountWeightTable,
      TAccountWeightTableAdmin extends string
        ? ReadonlySignerAccount<TAccountWeightTableAdmin> &
            IAccountSignerMeta<TAccountWeightTableAdmin>
        : TAccountWeightTableAdmin,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountRestakingProgramId extends string
        ? ReadonlyAccount<TAccountRestakingProgramId>
        : TAccountRestakingProgramId,
      ...TRemainingAccounts,
    ]
  >;

export type AdminUpdateWeightTableInstructionData = {
  discriminator: number;
  ncnEpoch: bigint;
  weight: bigint;
};

export type AdminUpdateWeightTableInstructionDataArgs = {
  ncnEpoch: number | bigint;
  weight: number | bigint;
};

export function getAdminUpdateWeightTableInstructionDataEncoder(): Encoder<AdminUpdateWeightTableInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['ncnEpoch', getU64Encoder()],
      ['weight', getU128Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: ADMIN_UPDATE_WEIGHT_TABLE_DISCRIMINATOR,
    })
  );
}

export function getAdminUpdateWeightTableInstructionDataDecoder(): Decoder<AdminUpdateWeightTableInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['ncnEpoch', getU64Decoder()],
    ['weight', getU128Decoder()],
  ]);
}

export function getAdminUpdateWeightTableInstructionDataCodec(): Codec<
  AdminUpdateWeightTableInstructionDataArgs,
  AdminUpdateWeightTableInstructionData
> {
  return combineCodec(
    getAdminUpdateWeightTableInstructionDataEncoder(),
    getAdminUpdateWeightTableInstructionDataDecoder()
  );
}

export type AdminUpdateWeightTableInput<
  TAccountNcn extends string = string,
  TAccountWeightTable extends string = string,
  TAccountWeightTableAdmin extends string = string,
  TAccountMint extends string = string,
  TAccountRestakingProgramId extends string = string,
> = {
  ncn: Address<TAccountNcn>;
  weightTable: Address<TAccountWeightTable>;
  weightTableAdmin: TransactionSigner<TAccountWeightTableAdmin>;
  mint: Address<TAccountMint>;
  restakingProgramId: Address<TAccountRestakingProgramId>;
  ncnEpoch: AdminUpdateWeightTableInstructionDataArgs['ncnEpoch'];
  weight: AdminUpdateWeightTableInstructionDataArgs['weight'];
};

export function getAdminUpdateWeightTableInstruction<
  TAccountNcn extends string,
  TAccountWeightTable extends string,
  TAccountWeightTableAdmin extends string,
  TAccountMint extends string,
  TAccountRestakingProgramId extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: AdminUpdateWeightTableInput<
    TAccountNcn,
    TAccountWeightTable,
    TAccountWeightTableAdmin,
    TAccountMint,
    TAccountRestakingProgramId
  >,
  config?: { programAddress?: TProgramAddress }
): AdminUpdateWeightTableInstruction<
  TProgramAddress,
  TAccountNcn,
  TAccountWeightTable,
  TAccountWeightTableAdmin,
  TAccountMint,
  TAccountRestakingProgramId
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    ncn: { value: input.ncn ?? null, isWritable: false },
    weightTable: { value: input.weightTable ?? null, isWritable: true },
    weightTableAdmin: {
      value: input.weightTableAdmin ?? null,
      isWritable: false,
    },
    mint: { value: input.mint ?? null, isWritable: false },
    restakingProgramId: {
      value: input.restakingProgramId ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.weightTable),
      getAccountMeta(accounts.weightTableAdmin),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.restakingProgramId),
    ],
    programAddress,
    data: getAdminUpdateWeightTableInstructionDataEncoder().encode(
      args as AdminUpdateWeightTableInstructionDataArgs
    ),
  } as AdminUpdateWeightTableInstruction<
    TProgramAddress,
    TAccountNcn,
    TAccountWeightTable,
    TAccountWeightTableAdmin,
    TAccountMint,
    TAccountRestakingProgramId
  >;

  return instruction;
}

export type ParsedAdminUpdateWeightTableInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    ncn: TAccountMetas[0];
    weightTable: TAccountMetas[1];
    weightTableAdmin: TAccountMetas[2];
    mint: TAccountMetas[3];
    restakingProgramId: TAccountMetas[4];
  };
  data: AdminUpdateWeightTableInstructionData;
};

export function parseAdminUpdateWeightTableInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedAdminUpdateWeightTableInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      ncn: getNextAccount(),
      weightTable: getNextAccount(),
      weightTableAdmin: getNextAccount(),
      mint: getNextAccount(),
      restakingProgramId: getNextAccount(),
    },
    data: getAdminUpdateWeightTableInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
