/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_EPOCH_ACCOUNT_DISCRIMINATOR = 27;

export function getCloseEpochAccountDiscriminatorBytes() {
  return getU8Encoder().encode(CLOSE_EPOCH_ACCOUNT_DISCRIMINATOR);
}

export type CloseEpochAccountInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountEpochState extends string | IAccountMeta<string> = string,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountAccountToClose extends string | IAccountMeta<string> = string,
  TAccountAccountPayer extends string | IAccountMeta<string> = string,
  TAccountDaoWallet extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountReceiverToClose extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountEpochState extends string
        ? WritableAccount<TAccountEpochState>
        : TAccountEpochState,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountAccountToClose extends string
        ? WritableAccount<TAccountAccountToClose>
        : TAccountAccountToClose,
      TAccountAccountPayer extends string
        ? WritableAccount<TAccountAccountPayer>
        : TAccountAccountPayer,
      TAccountDaoWallet extends string
        ? WritableAccount<TAccountDaoWallet>
        : TAccountDaoWallet,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountReceiverToClose extends string
        ? WritableAccount<TAccountReceiverToClose>
        : TAccountReceiverToClose,
      ...TRemainingAccounts,
    ]
  >;

export type CloseEpochAccountInstructionData = {
  discriminator: number;
  epoch: bigint;
};

export type CloseEpochAccountInstructionDataArgs = { epoch: number | bigint };

export function getCloseEpochAccountInstructionDataEncoder(): Encoder<CloseEpochAccountInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CLOSE_EPOCH_ACCOUNT_DISCRIMINATOR })
  );
}

export function getCloseEpochAccountInstructionDataDecoder(): Decoder<CloseEpochAccountInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getCloseEpochAccountInstructionDataCodec(): Codec<
  CloseEpochAccountInstructionDataArgs,
  CloseEpochAccountInstructionData
> {
  return combineCodec(
    getCloseEpochAccountInstructionDataEncoder(),
    getCloseEpochAccountInstructionDataDecoder()
  );
}

export type CloseEpochAccountInput<
  TAccountEpochState extends string = string,
  TAccountConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountAccountToClose extends string = string,
  TAccountAccountPayer extends string = string,
  TAccountDaoWallet extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountReceiverToClose extends string = string,
> = {
  epochState: Address<TAccountEpochState>;
  config: Address<TAccountConfig>;
  ncn: Address<TAccountNcn>;
  accountToClose: Address<TAccountAccountToClose>;
  accountPayer: Address<TAccountAccountPayer>;
  daoWallet: Address<TAccountDaoWallet>;
  systemProgram?: Address<TAccountSystemProgram>;
  receiverToClose?: Address<TAccountReceiverToClose>;
  epoch: CloseEpochAccountInstructionDataArgs['epoch'];
};

export function getCloseEpochAccountInstruction<
  TAccountEpochState extends string,
  TAccountConfig extends string,
  TAccountNcn extends string,
  TAccountAccountToClose extends string,
  TAccountAccountPayer extends string,
  TAccountDaoWallet extends string,
  TAccountSystemProgram extends string,
  TAccountReceiverToClose extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: CloseEpochAccountInput<
    TAccountEpochState,
    TAccountConfig,
    TAccountNcn,
    TAccountAccountToClose,
    TAccountAccountPayer,
    TAccountDaoWallet,
    TAccountSystemProgram,
    TAccountReceiverToClose
  >,
  config?: { programAddress?: TProgramAddress }
): CloseEpochAccountInstruction<
  TProgramAddress,
  TAccountEpochState,
  TAccountConfig,
  TAccountNcn,
  TAccountAccountToClose,
  TAccountAccountPayer,
  TAccountDaoWallet,
  TAccountSystemProgram,
  TAccountReceiverToClose
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    epochState: { value: input.epochState ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    ncn: { value: input.ncn ?? null, isWritable: false },
    accountToClose: { value: input.accountToClose ?? null, isWritable: true },
    accountPayer: { value: input.accountPayer ?? null, isWritable: true },
    daoWallet: { value: input.daoWallet ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    receiverToClose: { value: input.receiverToClose ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.epochState),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.accountToClose),
      getAccountMeta(accounts.accountPayer),
      getAccountMeta(accounts.daoWallet),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.receiverToClose),
    ],
    programAddress,
    data: getCloseEpochAccountInstructionDataEncoder().encode(
      args as CloseEpochAccountInstructionDataArgs
    ),
  } as CloseEpochAccountInstruction<
    TProgramAddress,
    TAccountEpochState,
    TAccountConfig,
    TAccountNcn,
    TAccountAccountToClose,
    TAccountAccountPayer,
    TAccountDaoWallet,
    TAccountSystemProgram,
    TAccountReceiverToClose
  >;

  return instruction;
}

export type ParsedCloseEpochAccountInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    epochState: TAccountMetas[0];
    config: TAccountMetas[1];
    ncn: TAccountMetas[2];
    accountToClose: TAccountMetas[3];
    accountPayer: TAccountMetas[4];
    daoWallet: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    receiverToClose?: TAccountMetas[7] | undefined;
  };
  data: CloseEpochAccountInstructionData;
};

export function parseCloseEpochAccountInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCloseEpochAccountInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === JITO_TIP_ROUTER_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      epochState: getNextAccount(),
      config: getNextAccount(),
      ncn: getNextAccount(),
      accountToClose: getNextAccount(),
      accountPayer: getNextAccount(),
      daoWallet: getNextAccount(),
      systemProgram: getNextAccount(),
      receiverToClose: getNextOptionalAccount(),
    },
    data: getCloseEpochAccountInstructionDataDecoder().decode(instruction.data),
  };
}
