/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const DISTRIBUTE_NCN_OPERATOR_REWARDS_DISCRIMINATOR = 17;

export function getDistributeNcnOperatorRewardsDiscriminatorBytes() {
  return getU8Encoder().encode(DISTRIBUTE_NCN_OPERATOR_REWARDS_DISCRIMINATOR);
}

export type DistributeNcnOperatorRewardsInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountRestakingConfig extends string | IAccountMeta<string> = string,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountOperator extends string | IAccountMeta<string> = string,
  TAccountNcnRewardRouter extends string | IAccountMeta<string> = string,
  TAccountRestakingProgram extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountRestakingConfig extends string
        ? ReadonlyAccount<TAccountRestakingConfig>
        : TAccountRestakingConfig,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountOperator extends string
        ? WritableAccount<TAccountOperator>
        : TAccountOperator,
      TAccountNcnRewardRouter extends string
        ? WritableAccount<TAccountNcnRewardRouter>
        : TAccountNcnRewardRouter,
      TAccountRestakingProgram extends string
        ? ReadonlyAccount<TAccountRestakingProgram>
        : TAccountRestakingProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DistributeNcnOperatorRewardsInstructionData = {
  discriminator: number;
  ncnFeeGroup: number;
  epoch: bigint;
};

export type DistributeNcnOperatorRewardsInstructionDataArgs = {
  ncnFeeGroup: number;
  epoch: number | bigint;
};

export function getDistributeNcnOperatorRewardsInstructionDataEncoder(): Encoder<DistributeNcnOperatorRewardsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['ncnFeeGroup', getU8Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: DISTRIBUTE_NCN_OPERATOR_REWARDS_DISCRIMINATOR,
    })
  );
}

export function getDistributeNcnOperatorRewardsInstructionDataDecoder(): Decoder<DistributeNcnOperatorRewardsInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['ncnFeeGroup', getU8Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getDistributeNcnOperatorRewardsInstructionDataCodec(): Codec<
  DistributeNcnOperatorRewardsInstructionDataArgs,
  DistributeNcnOperatorRewardsInstructionData
> {
  return combineCodec(
    getDistributeNcnOperatorRewardsInstructionDataEncoder(),
    getDistributeNcnOperatorRewardsInstructionDataDecoder()
  );
}

export type DistributeNcnOperatorRewardsInput<
  TAccountRestakingConfig extends string = string,
  TAccountConfig extends string = string,
  TAccountNcn extends string = string,
  TAccountOperator extends string = string,
  TAccountNcnRewardRouter extends string = string,
  TAccountRestakingProgram extends string = string,
> = {
  restakingConfig: Address<TAccountRestakingConfig>;
  config: Address<TAccountConfig>;
  ncn: Address<TAccountNcn>;
  operator: Address<TAccountOperator>;
  ncnRewardRouter: Address<TAccountNcnRewardRouter>;
  restakingProgram: Address<TAccountRestakingProgram>;
  ncnFeeGroup: DistributeNcnOperatorRewardsInstructionDataArgs['ncnFeeGroup'];
  epoch: DistributeNcnOperatorRewardsInstructionDataArgs['epoch'];
};

export function getDistributeNcnOperatorRewardsInstruction<
  TAccountRestakingConfig extends string,
  TAccountConfig extends string,
  TAccountNcn extends string,
  TAccountOperator extends string,
  TAccountNcnRewardRouter extends string,
  TAccountRestakingProgram extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: DistributeNcnOperatorRewardsInput<
    TAccountRestakingConfig,
    TAccountConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountNcnRewardRouter,
    TAccountRestakingProgram
  >,
  config?: { programAddress?: TProgramAddress }
): DistributeNcnOperatorRewardsInstruction<
  TProgramAddress,
  TAccountRestakingConfig,
  TAccountConfig,
  TAccountNcn,
  TAccountOperator,
  TAccountNcnRewardRouter,
  TAccountRestakingProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    restakingConfig: {
      value: input.restakingConfig ?? null,
      isWritable: false,
    },
    config: { value: input.config ?? null, isWritable: false },
    ncn: { value: input.ncn ?? null, isWritable: false },
    operator: { value: input.operator ?? null, isWritable: true },
    ncnRewardRouter: { value: input.ncnRewardRouter ?? null, isWritable: true },
    restakingProgram: {
      value: input.restakingProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.restakingConfig),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.ncnRewardRouter),
      getAccountMeta(accounts.restakingProgram),
    ],
    programAddress,
    data: getDistributeNcnOperatorRewardsInstructionDataEncoder().encode(
      args as DistributeNcnOperatorRewardsInstructionDataArgs
    ),
  } as DistributeNcnOperatorRewardsInstruction<
    TProgramAddress,
    TAccountRestakingConfig,
    TAccountConfig,
    TAccountNcn,
    TAccountOperator,
    TAccountNcnRewardRouter,
    TAccountRestakingProgram
  >;

  return instruction;
}

export type ParsedDistributeNcnOperatorRewardsInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    restakingConfig: TAccountMetas[0];
    config: TAccountMetas[1];
    ncn: TAccountMetas[2];
    operator: TAccountMetas[3];
    ncnRewardRouter: TAccountMetas[4];
    restakingProgram: TAccountMetas[5];
  };
  data: DistributeNcnOperatorRewardsInstructionData;
};

export function parseDistributeNcnOperatorRewardsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedDistributeNcnOperatorRewardsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      restakingConfig: getNextAccount(),
      config: getNextAccount(),
      ncn: getNextAccount(),
      operator: getNextAccount(),
      ncnRewardRouter: getNextAccount(),
      restakingProgram: getNextAccount(),
    },
    data: getDistributeNcnOperatorRewardsInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
