/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const REALLOC_BALLOT_BOX_DISCRIMINATOR = 25;

export function getReallocBallotBoxDiscriminatorBytes() {
  return getU8Encoder().encode(REALLOC_BALLOT_BOX_DISCRIMINATOR);
}

export type ReallocBallotBoxInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountConfig extends string | IAccountMeta<string> = string,
  TAccountBallotBox extends string | IAccountMeta<string> = string,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBallotBox extends string
        ? WritableAccount<TAccountBallotBox>
        : TAccountBallotBox,
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ReallocBallotBoxInstructionData = {
  discriminator: number;
  epoch: bigint;
};

export type ReallocBallotBoxInstructionDataArgs = { epoch: number | bigint };

export function getReallocBallotBoxInstructionDataEncoder(): Encoder<ReallocBallotBoxInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: REALLOC_BALLOT_BOX_DISCRIMINATOR })
  );
}

export function getReallocBallotBoxInstructionDataDecoder(): Decoder<ReallocBallotBoxInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getReallocBallotBoxInstructionDataCodec(): Codec<
  ReallocBallotBoxInstructionDataArgs,
  ReallocBallotBoxInstructionData
> {
  return combineCodec(
    getReallocBallotBoxInstructionDataEncoder(),
    getReallocBallotBoxInstructionDataDecoder()
  );
}

export type ReallocBallotBoxInput<
  TAccountConfig extends string = string,
  TAccountBallotBox extends string = string,
  TAccountNcn extends string = string,
  TAccountPayer extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  config: Address<TAccountConfig>;
  ballotBox: Address<TAccountBallotBox>;
  ncn: Address<TAccountNcn>;
  payer: TransactionSigner<TAccountPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  epoch: ReallocBallotBoxInstructionDataArgs['epoch'];
};

export function getReallocBallotBoxInstruction<
  TAccountConfig extends string,
  TAccountBallotBox extends string,
  TAccountNcn extends string,
  TAccountPayer extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: ReallocBallotBoxInput<
    TAccountConfig,
    TAccountBallotBox,
    TAccountNcn,
    TAccountPayer,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): ReallocBallotBoxInstruction<
  TProgramAddress,
  TAccountConfig,
  TAccountBallotBox,
  TAccountNcn,
  TAccountPayer,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
    ballotBox: { value: input.ballotBox ?? null, isWritable: true },
    ncn: { value: input.ncn ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.ballotBox),
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getReallocBallotBoxInstructionDataEncoder().encode(
      args as ReallocBallotBoxInstructionDataArgs
    ),
  } as ReallocBallotBoxInstruction<
    TProgramAddress,
    TAccountConfig,
    TAccountBallotBox,
    TAccountNcn,
    TAccountPayer,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedReallocBallotBoxInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
    ballotBox: TAccountMetas[1];
    ncn: TAccountMetas[2];
    payer: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: ReallocBallotBoxInstructionData;
};

export function parseReallocBallotBoxInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedReallocBallotBoxInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      config: getNextAccount(),
      ballotBox: getNextAccount(),
      ncn: getNextAccount(),
      payer: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getReallocBallotBoxInstructionDataDecoder().decode(instruction.data),
  };
}
