/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const ROUTE_NCN_REWARDS_DISCRIMINATOR = 19;

export function getRouteNcnRewardsDiscriminatorBytes() {
  return getU8Encoder().encode(ROUTE_NCN_REWARDS_DISCRIMINATOR);
}

export type RouteNcnRewardsInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountOperator extends string | IAccountMeta<string> = string,
  TAccountOperatorSnapshot extends string | IAccountMeta<string> = string,
  TAccountNcnRewardRouter extends string | IAccountMeta<string> = string,
  TAccountNcnRewardReceiver extends string | IAccountMeta<string> = string,
  TAccountRestakingProgram extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountOperator extends string
        ? ReadonlyAccount<TAccountOperator>
        : TAccountOperator,
      TAccountOperatorSnapshot extends string
        ? ReadonlyAccount<TAccountOperatorSnapshot>
        : TAccountOperatorSnapshot,
      TAccountNcnRewardRouter extends string
        ? WritableAccount<TAccountNcnRewardRouter>
        : TAccountNcnRewardRouter,
      TAccountNcnRewardReceiver extends string
        ? WritableAccount<TAccountNcnRewardReceiver>
        : TAccountNcnRewardReceiver,
      TAccountRestakingProgram extends string
        ? ReadonlyAccount<TAccountRestakingProgram>
        : TAccountRestakingProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RouteNcnRewardsInstructionData = {
  discriminator: number;
  ncnFeeGroup: number;
  maxIterations: number;
  epoch: bigint;
};

export type RouteNcnRewardsInstructionDataArgs = {
  ncnFeeGroup: number;
  maxIterations: number;
  epoch: number | bigint;
};

export function getRouteNcnRewardsInstructionDataEncoder(): Encoder<RouteNcnRewardsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['ncnFeeGroup', getU8Encoder()],
      ['maxIterations', getU16Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ROUTE_NCN_REWARDS_DISCRIMINATOR })
  );
}

export function getRouteNcnRewardsInstructionDataDecoder(): Decoder<RouteNcnRewardsInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['ncnFeeGroup', getU8Decoder()],
    ['maxIterations', getU16Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getRouteNcnRewardsInstructionDataCodec(): Codec<
  RouteNcnRewardsInstructionDataArgs,
  RouteNcnRewardsInstructionData
> {
  return combineCodec(
    getRouteNcnRewardsInstructionDataEncoder(),
    getRouteNcnRewardsInstructionDataDecoder()
  );
}

export type RouteNcnRewardsInput<
  TAccountNcn extends string = string,
  TAccountOperator extends string = string,
  TAccountOperatorSnapshot extends string = string,
  TAccountNcnRewardRouter extends string = string,
  TAccountNcnRewardReceiver extends string = string,
  TAccountRestakingProgram extends string = string,
> = {
  ncn: Address<TAccountNcn>;
  operator: Address<TAccountOperator>;
  operatorSnapshot: Address<TAccountOperatorSnapshot>;
  ncnRewardRouter: Address<TAccountNcnRewardRouter>;
  ncnRewardReceiver: Address<TAccountNcnRewardReceiver>;
  restakingProgram: Address<TAccountRestakingProgram>;
  ncnFeeGroup: RouteNcnRewardsInstructionDataArgs['ncnFeeGroup'];
  maxIterations: RouteNcnRewardsInstructionDataArgs['maxIterations'];
  epoch: RouteNcnRewardsInstructionDataArgs['epoch'];
};

export function getRouteNcnRewardsInstruction<
  TAccountNcn extends string,
  TAccountOperator extends string,
  TAccountOperatorSnapshot extends string,
  TAccountNcnRewardRouter extends string,
  TAccountNcnRewardReceiver extends string,
  TAccountRestakingProgram extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: RouteNcnRewardsInput<
    TAccountNcn,
    TAccountOperator,
    TAccountOperatorSnapshot,
    TAccountNcnRewardRouter,
    TAccountNcnRewardReceiver,
    TAccountRestakingProgram
  >,
  config?: { programAddress?: TProgramAddress }
): RouteNcnRewardsInstruction<
  TProgramAddress,
  TAccountNcn,
  TAccountOperator,
  TAccountOperatorSnapshot,
  TAccountNcnRewardRouter,
  TAccountNcnRewardReceiver,
  TAccountRestakingProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    ncn: { value: input.ncn ?? null, isWritable: false },
    operator: { value: input.operator ?? null, isWritable: false },
    operatorSnapshot: {
      value: input.operatorSnapshot ?? null,
      isWritable: false,
    },
    ncnRewardRouter: { value: input.ncnRewardRouter ?? null, isWritable: true },
    ncnRewardReceiver: {
      value: input.ncnRewardReceiver ?? null,
      isWritable: true,
    },
    restakingProgram: {
      value: input.restakingProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.operator),
      getAccountMeta(accounts.operatorSnapshot),
      getAccountMeta(accounts.ncnRewardRouter),
      getAccountMeta(accounts.ncnRewardReceiver),
      getAccountMeta(accounts.restakingProgram),
    ],
    programAddress,
    data: getRouteNcnRewardsInstructionDataEncoder().encode(
      args as RouteNcnRewardsInstructionDataArgs
    ),
  } as RouteNcnRewardsInstruction<
    TProgramAddress,
    TAccountNcn,
    TAccountOperator,
    TAccountOperatorSnapshot,
    TAccountNcnRewardRouter,
    TAccountNcnRewardReceiver,
    TAccountRestakingProgram
  >;

  return instruction;
}

export type ParsedRouteNcnRewardsInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    ncn: TAccountMetas[0];
    operator: TAccountMetas[1];
    operatorSnapshot: TAccountMetas[2];
    ncnRewardRouter: TAccountMetas[3];
    ncnRewardReceiver: TAccountMetas[4];
    restakingProgram: TAccountMetas[5];
  };
  data: RouteNcnRewardsInstructionData;
};

export function parseRouteNcnRewardsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRouteNcnRewardsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      ncn: getNextAccount(),
      operator: getNextAccount(),
      operatorSnapshot: getNextAccount(),
      ncnRewardRouter: getNextAccount(),
      ncnRewardReceiver: getNextAccount(),
      restakingProgram: getNextAccount(),
    },
    data: getRouteNcnRewardsInstructionDataDecoder().decode(instruction.data),
  };
}
