/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type WritableAccount,
} from '@solana/web3.js';
import { JITO_TIP_ROUTER_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const ROUTE_BASE_REWARDS_DISCRIMINATOR = 18;

export function getRouteBaseRewardsDiscriminatorBytes() {
  return getU8Encoder().encode(ROUTE_BASE_REWARDS_DISCRIMINATOR);
}

export type RouteBaseRewardsInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountEpochSnapshot extends string | IAccountMeta<string> = string,
  TAccountBallotBox extends string | IAccountMeta<string> = string,
  TAccountBaseRewardRouter extends string | IAccountMeta<string> = string,
  TAccountBaseRewardReceiver extends string | IAccountMeta<string> = string,
  TAccountRestakingProgram extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountEpochSnapshot extends string
        ? ReadonlyAccount<TAccountEpochSnapshot>
        : TAccountEpochSnapshot,
      TAccountBallotBox extends string
        ? ReadonlyAccount<TAccountBallotBox>
        : TAccountBallotBox,
      TAccountBaseRewardRouter extends string
        ? WritableAccount<TAccountBaseRewardRouter>
        : TAccountBaseRewardRouter,
      TAccountBaseRewardReceiver extends string
        ? WritableAccount<TAccountBaseRewardReceiver>
        : TAccountBaseRewardReceiver,
      TAccountRestakingProgram extends string
        ? ReadonlyAccount<TAccountRestakingProgram>
        : TAccountRestakingProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RouteBaseRewardsInstructionData = {
  discriminator: number;
  maxIterations: number;
  epoch: bigint;
};

export type RouteBaseRewardsInstructionDataArgs = {
  maxIterations: number;
  epoch: number | bigint;
};

export function getRouteBaseRewardsInstructionDataEncoder(): Encoder<RouteBaseRewardsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['maxIterations', getU16Encoder()],
      ['epoch', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: ROUTE_BASE_REWARDS_DISCRIMINATOR })
  );
}

export function getRouteBaseRewardsInstructionDataDecoder(): Decoder<RouteBaseRewardsInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['maxIterations', getU16Decoder()],
    ['epoch', getU64Decoder()],
  ]);
}

export function getRouteBaseRewardsInstructionDataCodec(): Codec<
  RouteBaseRewardsInstructionDataArgs,
  RouteBaseRewardsInstructionData
> {
  return combineCodec(
    getRouteBaseRewardsInstructionDataEncoder(),
    getRouteBaseRewardsInstructionDataDecoder()
  );
}

export type RouteBaseRewardsInput<
  TAccountNcn extends string = string,
  TAccountEpochSnapshot extends string = string,
  TAccountBallotBox extends string = string,
  TAccountBaseRewardRouter extends string = string,
  TAccountBaseRewardReceiver extends string = string,
  TAccountRestakingProgram extends string = string,
> = {
  ncn: Address<TAccountNcn>;
  epochSnapshot: Address<TAccountEpochSnapshot>;
  ballotBox: Address<TAccountBallotBox>;
  baseRewardRouter: Address<TAccountBaseRewardRouter>;
  baseRewardReceiver: Address<TAccountBaseRewardReceiver>;
  restakingProgram: Address<TAccountRestakingProgram>;
  maxIterations: RouteBaseRewardsInstructionDataArgs['maxIterations'];
  epoch: RouteBaseRewardsInstructionDataArgs['epoch'];
};

export function getRouteBaseRewardsInstruction<
  TAccountNcn extends string,
  TAccountEpochSnapshot extends string,
  TAccountBallotBox extends string,
  TAccountBaseRewardRouter extends string,
  TAccountBaseRewardReceiver extends string,
  TAccountRestakingProgram extends string,
  TProgramAddress extends Address = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
>(
  input: RouteBaseRewardsInput<
    TAccountNcn,
    TAccountEpochSnapshot,
    TAccountBallotBox,
    TAccountBaseRewardRouter,
    TAccountBaseRewardReceiver,
    TAccountRestakingProgram
  >,
  config?: { programAddress?: TProgramAddress }
): RouteBaseRewardsInstruction<
  TProgramAddress,
  TAccountNcn,
  TAccountEpochSnapshot,
  TAccountBallotBox,
  TAccountBaseRewardRouter,
  TAccountBaseRewardReceiver,
  TAccountRestakingProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_TIP_ROUTER_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    ncn: { value: input.ncn ?? null, isWritable: false },
    epochSnapshot: { value: input.epochSnapshot ?? null, isWritable: false },
    ballotBox: { value: input.ballotBox ?? null, isWritable: false },
    baseRewardRouter: {
      value: input.baseRewardRouter ?? null,
      isWritable: true,
    },
    baseRewardReceiver: {
      value: input.baseRewardReceiver ?? null,
      isWritable: true,
    },
    restakingProgram: {
      value: input.restakingProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.epochSnapshot),
      getAccountMeta(accounts.ballotBox),
      getAccountMeta(accounts.baseRewardRouter),
      getAccountMeta(accounts.baseRewardReceiver),
      getAccountMeta(accounts.restakingProgram),
    ],
    programAddress,
    data: getRouteBaseRewardsInstructionDataEncoder().encode(
      args as RouteBaseRewardsInstructionDataArgs
    ),
  } as RouteBaseRewardsInstruction<
    TProgramAddress,
    TAccountNcn,
    TAccountEpochSnapshot,
    TAccountBallotBox,
    TAccountBaseRewardRouter,
    TAccountBaseRewardReceiver,
    TAccountRestakingProgram
  >;

  return instruction;
}

export type ParsedRouteBaseRewardsInstruction<
  TProgram extends string = typeof JITO_TIP_ROUTER_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    ncn: TAccountMetas[0];
    epochSnapshot: TAccountMetas[1];
    ballotBox: TAccountMetas[2];
    baseRewardRouter: TAccountMetas[3];
    baseRewardReceiver: TAccountMetas[4];
    restakingProgram: TAccountMetas[5];
  };
  data: RouteBaseRewardsInstructionData;
};

export function parseRouteBaseRewardsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedRouteBaseRewardsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      ncn: getNextAccount(),
      epochSnapshot: getNextAccount(),
      ballotBox: getNextAccount(),
      baseRewardRouter: getNextAccount(),
      baseRewardReceiver: getNextAccount(),
      restakingProgram: getNextAccount(),
    },
    data: getRouteBaseRewardsInstructionDataDecoder().decode(instruction.data),
  };
}
