/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/web3.js';
import {
  getNcnFeeGroupDecoder,
  getNcnFeeGroupEncoder,
  getVaultRewardRouteDecoder,
  getVaultRewardRouteEncoder,
  type NcnFeeGroup,
  type NcnFeeGroupArgs,
  type VaultRewardRoute,
  type VaultRewardRouteArgs,
} from '../types';

export type NcnRewardRouter = {
  discriminator: bigint;
  ncnFeeGroup: NcnFeeGroup;
  operator: Address;
  ncn: Address;
  ncnEpoch: bigint;
  bump: number;
  slotCreated: bigint;
  totalRewards: bigint;
  rewardPool: bigint;
  rewardsProcessed: bigint;
  operatorRewards: bigint;
  reserved: Array<number>;
  vaultRewardRoutes: Array<VaultRewardRoute>;
};

export type NcnRewardRouterArgs = {
  discriminator: number | bigint;
  ncnFeeGroup: NcnFeeGroupArgs;
  operator: Address;
  ncn: Address;
  ncnEpoch: number | bigint;
  bump: number;
  slotCreated: number | bigint;
  totalRewards: number | bigint;
  rewardPool: number | bigint;
  rewardsProcessed: number | bigint;
  operatorRewards: number | bigint;
  reserved: Array<number>;
  vaultRewardRoutes: Array<VaultRewardRouteArgs>;
};

export function getNcnRewardRouterEncoder(): Encoder<NcnRewardRouterArgs> {
  return getStructEncoder([
    ['discriminator', getU64Encoder()],
    ['ncnFeeGroup', getNcnFeeGroupEncoder()],
    ['operator', getAddressEncoder()],
    ['ncn', getAddressEncoder()],
    ['ncnEpoch', getU64Encoder()],
    ['bump', getU8Encoder()],
    ['slotCreated', getU64Encoder()],
    ['totalRewards', getU64Encoder()],
    ['rewardPool', getU64Encoder()],
    ['rewardsProcessed', getU64Encoder()],
    ['operatorRewards', getU64Encoder()],
    ['reserved', getArrayEncoder(getU8Encoder(), { size: 128 })],
    [
      'vaultRewardRoutes',
      getArrayEncoder(getVaultRewardRouteEncoder(), { size: 32 }),
    ],
  ]);
}

export function getNcnRewardRouterDecoder(): Decoder<NcnRewardRouter> {
  return getStructDecoder([
    ['discriminator', getU64Decoder()],
    ['ncnFeeGroup', getNcnFeeGroupDecoder()],
    ['operator', getAddressDecoder()],
    ['ncn', getAddressDecoder()],
    ['ncnEpoch', getU64Decoder()],
    ['bump', getU8Decoder()],
    ['slotCreated', getU64Decoder()],
    ['totalRewards', getU64Decoder()],
    ['rewardPool', getU64Decoder()],
    ['rewardsProcessed', getU64Decoder()],
    ['operatorRewards', getU64Decoder()],
    ['reserved', getArrayDecoder(getU8Decoder(), { size: 128 })],
    [
      'vaultRewardRoutes',
      getArrayDecoder(getVaultRewardRouteDecoder(), { size: 32 }),
    ],
  ]);
}

export function getNcnRewardRouterCodec(): Codec<
  NcnRewardRouterArgs,
  NcnRewardRouter
> {
  return combineCodec(getNcnRewardRouterEncoder(), getNcnRewardRouterDecoder());
}

export function decodeNcnRewardRouter<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<NcnRewardRouter, TAddress>;
export function decodeNcnRewardRouter<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<NcnRewardRouter, TAddress>;
export function decodeNcnRewardRouter<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
  | Account<NcnRewardRouter, TAddress>
  | MaybeAccount<NcnRewardRouter, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getNcnRewardRouterDecoder()
  );
}

export async function fetchNcnRewardRouter<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<NcnRewardRouter, TAddress>> {
  const maybeAccount = await fetchMaybeNcnRewardRouter(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeNcnRewardRouter<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<NcnRewardRouter, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeNcnRewardRouter(maybeAccount);
}

export async function fetchAllNcnRewardRouter(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<NcnRewardRouter>[]> {
  const maybeAccounts = await fetchAllMaybeNcnRewardRouter(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeNcnRewardRouter(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<NcnRewardRouter>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeNcnRewardRouter(maybeAccount)
  );
}
